<?php

/**
 * Implements hook_nexteuropa_cookie_consent_register_cookie().
 */
function nexteuropa_cookie_consent_test_nexteuropa_cookie_consent_register_cookie() {
  return array(
    'override' => array(
      'languages' => array('en'),
      'machine_name' => 'override_machine_name',
      'fields' => array(
        'name' => array(
          'en' => 'overridden_name',
        ),
        'description' => array(
          'en' => 'overridden description.',
        ),
      ),
      // Won't be overridden.
      'type' => 'overridden_type',
      'managed' => 'overridden_managed',
      'default_language' => 'overridden_en',
    ),
    'avocado',
  );
}
