<?php

/**
 * Implements hook_nexteuropa_cookie_consent_register_cookie().
 */
function nexteuropa_cookie_consent_test_nexteuropa_cookie_consent_register_cookie() {
  return array(
    'override' => array(
      'default_language' => 'en',
      'languages' => array('en'),
      'domains' => array('overridden_domain'),
      'machine_name' => 'override_machine_name',
      'managed' => FALSE,
      'fields' => array(
        'name' => array(
          'en' => 'overridden_name',
        ),
        'description' => array(
          'en' => 'overridden description.',
        ),
      ),
      // Won't be overridden.
      'type' => 'overridden schema',
      'default' => 'overridden_default',
      'version' => 'overridden version',
    ),
    'avocado',
  );
}
